all: pa3

pa: pintaalat.c jaagrid.c maapintaala.c
	gcc -g -Wall -o pintaalat pintaalat.c jaagrid.c maapintaala.c -lm

pa3: pintaalat.c jaagrid.c maapintaala.c
	gcc -g -Wall -o pintaalat pintaalat.c jaagrid.c maapintaala.c -lm -O3
